language: node_js
notifications:
  email: false
node_js:
  - node
  - lts/*
  - 8
before_script :
  - npm install -g grunt-cli
after_success:
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
