name: Test or Release

on:
  - push
  - pull_request

jobs:
  test-or-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: |
          - args: [--frozen-lockfile, --no-verify-store-integrity]
    - name: Test
      run: npm test
    - name: Coverage
      uses: codecov/codecov-action@v3
    - name: Publish
      uses: cycjimmy/semantic-release-action@v3
      with:
        branches: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
